### ISSUE TITLE
Loading new avatar Destroy previous one

### ISSUE THREAD

**Issue by Kushulain** [readyplayerme/rpm-unity-sdk-core#132]
In [AvatarProcessor.cs](https://github.com/readyplayerme/rpm-unity-sdk-core/blob/main/Runtime/Operations/AvatarProcessor.cs#L48) we have the following function line 48:

```
        private AvatarContext ProcessAvatarGameObject(AvatarContext context)
        {
            GameObject oldInstance = GameObject.Find(context.AvatarUri.Guid);
            if (oldInstance)
            {
                Object.DestroyImmediate(oldInstance);
            }

            ((Object) context.Data).name = context.AvatarUri.Guid;

            return context;
        }
```

It's triggered when loading a new avatar. It attempts to search and destroy the previous avatar with the same GUID in the scene.

In our game, the player can record his movement, once he is done, he can see a copy of his avatar doing the movements.

Here is few problems:
1. We should really be able to toggle this behavior. Like `LoadAvatar(string url, bool removePreviousOne = true)` when we need multiple instance of the same avatar.
2. It's not documented and it's hard to figure out what's happening and why, when this happen.
3.  [GameObject.Find()](https://docs.unity3d.com/ScriptReference/GameObject.Find.html) can be slow for heavy scene, and will trigger a freeze of the app.

Workaround: rename Avatar gameobject after it's instantiated.

(I have been playing with ReadyPlayerMe for a few days, and except this little detail my experience of the implementation was really smooth & fun)

**Comment by HarrisonHough** [comment]
Yep, this functionality is intentional for a few reasons: 
1. but being able to replace the avatar instance like this we can update the avatar (redownload and replace) if we detect that the avatar has been customized or updated since the last time it was loaded
2. We generally aim to provide personal avatars, so having multiple copies of the same exact avatar isn't the intended use case. 

However, if you do want to load the same avatar multiple times it would be better to duplicate or make a copy of the existing avatar, loading from file and/or downloading the same avatar file multiple times isn't very efficient. It would be more optimal to load it once and then duplicate it as many times as needed. 

In any case, we appreciate the feedback, I will pass it on to the team for us to discuss internally.

**Comment by Kushulain** [comment]
Okay, I'll probably use Instantiation then. Good point, thank you for you feedback.

**Comment by HarrisonHough** [comment]
No problem. 
As for the point you had about the [GameObject.Find()](https://docs.unity3d.com/ScriptReference/GameObject.Find.html). That is completely valid, and it is something that has been on the radar for us to improve. We have a task to work on a better solution for this, most likely it will involve keeping track of all avatars loaded into a scene something like an avatar manager for example. 

Thanks for understanding. Let us know if you have any further issues.
