### ISSUE TITLE
404 error on "Check for Updates"

### ISSUE THREAD

**Issue by Paul-Auguste** [readyplayerme/rpm-unity-sdk-core#40]
**Describe the bug**
By clicking on the "Check For Updates" button it returns me a 404 error.

`Failed to fetch com.readyplayerme.core releases. Error: HTTP/1.1 404 Not Found 
UnityEngine.Debug:Log (object)
ReadyPlayerMe.Core.Editor.ModuleUpdater/<FetchReleases>d__9:MoveNext () (at Library/PackageCache/com.readyplayerme.core@39d3c866dc/Editor/Module Management/ModuleUpdater.cs:88)
UnityEngine.UnitySynchronizationContext:ExecuteTasks () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)`

**To Reproduce**
1. Install the core module
2. Click on "Check For Updates"

**Mac Editor :**
 - Ready Player Me Core version

**Comment by HarrisonHough** [comment]
Thanks for reporting this issue! 

Can you check the manifest.json in your project? I believe this issue was caused by the changed of repository names. 
You should be able to fix by either manually updating the URL's of the modules in there 
![image](https://user-images.githubusercontent.com/7085672/216254351-c2f57265-1f09-40d4-8891-6c82ea86e017.png)

or you a clean install of the latest core module should also fix. 
I can add this to the docs But after a clean install of Unity Core 0.1.1 this should no longer occur.

**Comment by Paul-Auguste** [comment]
That was exactly this.

Fixed it by modifying :
"com.readyplayerme.core": "https://github.com/readyplayerme/Unity-core.git"
into
"com.readyplayerme.core": "https://github.com/readyplayerme/rpm-unity-sdk-core.git#v0.1.1"

Thanks !
